### ISSUE TITLE
[Backend] As a user, I can see a timeframe bar on the Detail screen

### ISSUE THREAD

**Issue by nkhanh44** [nimblehq/nimble-crypto-ios#42]
## Why

- The user should be able to see the timeframe bar on the Detail screen.

## Acceptance Criteria

- When the user navigates to the Detail screen and selects the timeframe `1D, 7D, 1M, 1Y, 5Y` the following API with the corresponding parameters is called: `GET /coins/{id}/market_chart`.

Parameters:
```
    id: “bitcoin”
    vs_currency:  “usd”
    days: “365"
```
for key days:
`1D, 7D, 1M, 1Y, 5Y` will have the value `1, 7, 30, 365, 5*365`.

- If the API returns success, the user will see the chart based on the selected timeframe (handled in integrate story).
- If the API returns an error, the user will see the error state using the default alert with the title is `Error`, the message's content is from the API response, and the confirm button's title is `Ok`.

The error response will look as follows:
``` JSON
{
  "error": "Could not find a coin with the given id"
}
```
## API Documents
- [Coingecko API document](https://www.coingecko.com/en/api/documentation).

**Comment by minhnimble** [comment]
This task is already implemented in #75
